version: '3.1'

services:

  php:
    build:
      context: docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./public_html:/var/www/public_html
    environment:
      PHP_IDE_CONFIG: serverName=PHPSTORM
      XDEBUG_SESSION: PHPSTORM
    networks:
      - app

  apache:
    build:
      context: docker/apache
    volumes:
      - ./public_html:/var/www/public_html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - db
    networks:
      - app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/public_html

  db:
    image: mariadb:latest
    restart: on-failure
    networks:
      - app
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: dev
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: wp
    volumes:
      - ./db_files/mariadb:/var/lib/mysql
      - ./db_files/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

networks:
  app:
    driver: bridge
